apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: guestbook-api
type: Opaque
stringData:
  MYSQL_HOST: mysql.guestbook-db.svc.cluster.local
  MYSQL_PORT: "3306"
  MYSQL_DB: guestbook
  MYSQL_USER: guestuser
  MYSQL_PASSWORD: guestpass
